### ISSUE TITLE
How to get password hashes from a local Sam file ?

### ISSUE THREAD

**Issue by skashish** [moyix/creddump#6]
As written in Documentation usage 

`usage: ./pwdump.py <system hive> <SAM hive>`.

Suppose, I have a local SAM file (say in the same directory as of pwdump.py) , and I want to extract password hashes from it, what will be the values  of the arguments `<system hive>` and `<SAM hive>`?

Thanks!

**Comment by moyix** [comment]
You also need the SYSTEM hive (usually found in `C:\windows\system32\config\system`). Then you could invoke it as:

`./pwdump.py SYSTEM SAM`

Also note that I haven't been keeping this up to date with new Windows versions. You may be better off checking out [creddump7](https://github.com/Neohapsis/creddump7), which is based on this code but has been updated to add Windows Vista and Windows 7 support.
